### ISSUE TITLE
Unable to use embedded structs with tags

### ISSUE THREAD

**Issue by c0mpressi0n** [Teamwork/kommentaar#65]
Getting the following panic when a response struct has an embedded pointer with tags. 

```
gareth@gareth-Virtual-Machine:~/go/src/github.com/teamwork/kommentaar$ kommentaar github.com/teamwork/kommentaar/example/
panic: interface conversion: ast.Expr is *ast.StarExpr, not *ast.Ident

goroutine 1 [running]:
github.com/teamwork/kommentaar/docparse.GetReference(0xc0000b97a0, 0x8ab43a, 0x4, 0x0, 0xc00029c2fb, 0x3, 0xc00002e7d0, 0x45, 0xa, 0x20, ...)
        /home/gareth/go/src/github.com/teamwork/kommentaar/docparse/find.go:296 +0x2298
github.com/teamwork/kommentaar/docparse.parseRefValue(0xc0000b97a0, 0x8ab43a, 0x4, 0xc00029c2fb, 0x3, 0xc00002e7d0, 0x45, 0xc00009bca0, 0x92f460, 0xc0000b9ab8)
        /home/gareth/go/src/github.com/teamwork/kommentaar/docparse/docparse.go:456 +0xe1
github.com/teamwork/kommentaar/docparse.ParseResponse(0xc0000b97a0, 0xc00002e7d0, 0x45, 0xc00029c2da, 0x24, 0x0, 0xc0002c4960, 0x0, 0x0)
        /home/gareth/go/src/github.com/teamwork/kommentaar/docparse/docparse.go:384 +0x182
github.com/teamwork/kommentaar/docparse.parseComment(0xc0000b97a0, 0xc00029c180, 0x17f, 0x7ffecc854eee, 0x27, 0xc00002e7d0, 0x45, 0x0, 0x0, 0x0, ...)
        /home/gareth/go/src/github.com/teamwork/kommentaar/docparse/docparse.go:302 +0x1402
github.com/teamwork/kommentaar/docparse.FindComments(0x92a580, 0xc00000e020, 0xc0000b97a0, 0x0, 0x8bac51)
        /home/gareth/go/src/github.com/teamwork/kommentaar/docparse/find.go:53 +0x274
main.start(0xc00013df00, 0x0, 0x0)
        /home/gareth/go/src/github.com/teamwork/kommentaar/main.go:91 +0x36e
main.main()
        /home/gareth/go/src/github.com/teamwork/kommentaar/main.go:23 +0x41
```

Can recreate with the kommentaar example by adding the following struct 
```
type Foo struct {
	*MyError `json:"test"`
}
```
and adding the above as a response.

**Comment by Carpetsmoker** [comment]
Looks like you need to read over `ast.StarExpr`. Patches welcome :-) Look at the other instances for `ast.StarExpr` on how to do that.

Easiest way to test that is to make a test case in `testdata` btw; below is a basic patch which does that (you'll have to make a corresponding `want.yaml` file as wel)

```
diff --git c/testdata/openapi2/src/struct-embed-tag/in.go i/testdata/openapi2/src/struct-embed-tag/in.go
new file mode 100644
index 0000000..12c16fb
--- /dev/null
+++ i/testdata/openapi2/src/struct-embed-tag/in.go
@@ -0,0 +1,15 @@
+package path
+
+// resp docs.
+type resp struct {
+	*other `json:"o"`
+}
+
+// other docs.
+type other struct {
+	Other string `json:"other"` // Other.
+}
+
+// POST /path
+//
+// Response 200: resp
```
